import { Category, Product, Inquiry, Analytics } from './types';

export const categories: Category[] = [
  {
    id: '1',
    name: 'Whole Spice',
    description: 'Pure, whole spices for the perfect blend',
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/i_want_the_202604072247.png-q6snRZgFeagrmHorH7yN9bnwPyqj0O.jpeg',
    isActive: true,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'Powder Spice',
    description: 'Fine powder spices for everyday cooking',
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Turmeric_-_now_202604072249.png-n2rdSUTQl2wzX5itnkJ4gluUDdOEay.jpeg',
    isActive: true,
    createdAt: '2024-01-20',
  },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Red Chilli',
    description: 'Premium whole red chillies with intense heat and flavor',
    category: 'whole-spice',
    price: 450,
    views: 1256,
    images: [
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/okay_another_spices%2C_202604072246.png-quRHhKOSp4u3NhP8KpJJi9biOE917H.jpeg',
    ],
    weight: '100g',
    benefits: ['Boosts metabolism', 'Rich in Vitamin C', 'Anti-inflammatory'],
    usage: 'Use in curries, pickles, and spice blends',
    isActive: true,
    createdAt: '2024-01-10',
  },
  {
    id: '2',
    name: 'Fennel Seeds',
    description: 'Premium whole fennel seeds with sweet aroma',
    category: 'whole-spice',
    price: 380,
    views: 890,
    images: [
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Fennel_-_now_202604072253.png-Ky8u8d5TPxng3ZsL79tv4tBZA8oN3S.jpeg',
    ],
    weight: '100g',
    benefits: ['Aids digestion', 'Freshens breath', 'Rich in antioxidants'],
    usage: 'Chew after meals or add to tea',
    isActive: true,
    createdAt: '2024-01-12',
  },
  {
    id: '3',
    name: 'Coriander Seeds',
    description: 'Whole coriander seeds with aromatic flavor',
    category: 'whole-spice',
    price: 320,
    views: 1045,
    images: [
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Coriander_-_best_202604072252.png-WkSeDyYLtoXC9tcf9j5fg96DDIUFK4.jpeg',
    ],
    weight: '100g',
    benefits: ['Improves digestion', 'Reduces inflammation', 'Lowers cholesterol'],
    usage: 'Toast and grind for curries or use whole in tempering',
    isActive: true,
    createdAt: '2024-01-14',
  },
  {
    id: '4',
    name: 'Cumin Seeds',
    description: 'Premium whole cumin with earthy flavor',
    category: 'whole-spice',
    price: 420,
    views: 2145,
    images: [
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Gemini_Generated_Image_xp0j04xp0j04xp0j.png-LHLpw24VdTO9qGX8hIuQGkBR1j3T2F.jpeg',
    ],
    weight: '100g',
    benefits: ['Boosts immunity', 'Aids digestion', 'Rich in iron'],
    usage: 'Use in curries, rice dishes, and seasoning',
    isActive: true,
    createdAt: '2024-01-18',
  },
  {
    id: '5',
    name: 'Turmeric Powder',
    description: 'Pure turmeric powder with high curcumin content',
    category: 'powder-spice',
    price: 380,
    views: 1567,
    images: [
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Turmeric_-_now_202604072249.png-n2rdSUTQl2wzX5itnkJ4gluUDdOEay.jpeg',
    ],
    weight: '200g',
    benefits: ['Anti-inflammatory', 'Improves skin', 'Boosts immunity'],
    usage: 'Add to curries, milk, or smoothies',
    isActive: true,
    createdAt: '2024-01-16',
  },
  {
    id: '6',
    name: 'Red Chilli Powder',
    description: 'Fine red chilli powder for authentic spice',
    category: 'powder-spice',
    price: 320,
    views: 1823,
    images: [
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/okay_another_spices%2C_202604072246.png-quRHhKOSp4u3NhP8KpJJi9biOE917H.jpeg',
    ],
    weight: '200g',
    benefits: ['Boosts metabolism', 'Anti-inflammatory', 'Improves blood flow'],
    usage: 'Use in curries, soups, and seasoning',
    isActive: true,
    createdAt: '2024-01-17',
  },
  {
    id: '7',
    name: 'Coriander Powder',
    description: 'Pure ground coriander with aromatic taste',
    category: 'powder-spice',
    price: 280,
    views: 956,
    images: [
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Coriander_-_best_202604072252.png-WkSeDyYLtoXC9tcf9j5fg96DDIUFK4.jpeg',
    ],
    weight: '200g',
    benefits: ['Aids digestion', 'Reduces bloating', 'Anti-bacterial'],
    usage: 'Add to curries, soups, and dressings',
    isActive: true,
    createdAt: '2024-01-19',
  },
  {
    id: '8',
    name: 'Cumin Powder',
    description: 'Fine cumin powder with rich aroma',
    category: 'powder-spice',
    price: 350,
    views: 1734,
    images: [
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Gemini_Generated_Image_xp0j04xp0j04xp0j.png-LHLpw24VdTO9qGX8hIuQGkBR1j3T2F.jpeg',
    ],
    weight: '200g',
    benefits: ['Boosts metabolism', 'Aids digestion', 'Rich in iron'],
    usage: 'Use in curries, rice, and seasoning',
    isActive: true,
    createdAt: '2024-01-21',
  },
];

export const inquiries: Inquiry[] = [
  {
    id: '1',
    name: 'Raj Kumar',
    email: 'raj.kumar@example.com',
    phone: '+91-9876543210',
    subject: 'Bulk order for restaurant',
    message: 'I am interested in bulk orders of turmeric and red chilli powder for my restaurant.',
    status: 'pending',
    createdAt: '2024-04-23',
  },
  {
    id: '2',
    name: 'Priya Singh',
    email: 'priya.singh@example.com',
    phone: '+91-9123456789',
    subject: 'Product quality inquiry',
    message: 'Can you provide certification details for organic spices?',
    status: 'in-progress',
    createdAt: '2024-04-22',
  },
  {
    id: '3',
    name: 'Arjun Patel',
    email: 'arjun.patel@example.com',
    phone: '+91-8765432109',
    subject: 'Delivery to Goa',
    message: 'Does your delivery service cover Goa? How long would it take?',
    status: 'resolved',
    createdAt: '2024-04-20',
  },
  {
    id: '4',
    name: 'Sneha Desai',
    email: 'sneha.desai@example.com',
    phone: '+91-7654321098',
    subject: 'Custom spice blend',
    message: 'Can you create a custom spice blend for our cafe?',
    status: 'pending',
    createdAt: '2024-04-21',
  },
  {
    id: '5',
    name: 'Vikram Sharma',
    email: 'vikram.sharma@example.com',
    phone: '+91-6543210987',
    subject: 'Wholesale pricing',
    message: 'Looking for wholesale pricing on multiple spice items.',
    status: 'in-progress',
    createdAt: '2024-04-19',
  },
];

export const analytics: Analytics = {
  totalUsersVisited: 15840,
  newUsers: 342,
  websiteTraffic: 45230,
  categoryStats: {
    wholeSvice: 8420,
    powderSpice: 6810,
  },
  trendingProducts: [
    { id: '4', name: 'Cumin Seeds', views: 2145 },
    { id: '6', name: 'Red Chilli Powder', views: 1823 },
    { id: '8', name: 'Cumin Powder', views: 1734 },
    { id: '1', name: 'Red Chilli', views: 1256 },
    { id: '5', name: 'Turmeric Powder', views: 1567 },
  ],
};
